{{- if .Values.api.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: swift-convert-ingress
  {{- if .Values.api.ingress.labels }}
  labels:
    {{ .Values.api.ingress.labels | toYaml | indent 4 }}
  {{- end }}
  {{- if .Values.api.ingress.annotations }}
  annotations:
    {{ .Values.api.ingress.annotations | toYaml | indent 4 }}
  {{- end }}

spec:
  ingressClassName: {{ .Values.api.ingress.className }}
  {{- if .Values.api.ingress.tls }}
  tls:
    {{- if .Values.api.ingress.tlsenabled }}
      {{- range .Values.api.ingress.tls }}
    - hosts:
          {{- range .hosts }}
        - {{ . | quote }}
          {{- end }}
      secretName: {{ .secretName }}
      {{- end }}
      {{- end }}
  {{- end }}
  rules:
    {{- range .Values.api.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $.Values.api.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "swift-convert-api.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
    {{- end }}
  {{- end }}