apiVersion: v1
kind: Service
metadata:
  name: {{ include "swift-convert-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "swift-convert-api.labels" . | nindent 4 }}
    {{- if .Values.service.labels }}
    {{ .Values.service.labels | toYaml | indent 4 }}
    {{- end }}
    {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    {{- include "swift-convert-api.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
    